# Generated by Django 6.0.5 on 2026-06-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('type', models.CharField(choices=[('seat', 'Seat'), ('aisle', 'Aisle')], max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['row', 'col'],
                'unique_together': {('row', 'col')},
            },
        ),
    ]
