# Generated by Django 6.0.5 on 2026-06-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alive_check', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='status',
            field=models.CharField(choices=[('alive', 'Alive'), ('dead', 'Dead'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
    ]
